version: '3'

networks:
  chess-bot:
    driver: bridge
    
services:

  selenium_standalone:
    container_name: selenium-chess
    image: selenium/standalone-chrome:130.0
    shm_size: 4gb
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    ports:
      - "7901:7900"
    networks:
      - chess-bot
      
  chess-com-bot:
    container_name: chess-com-bot
    build: ..
    depends_on:
      - selenium_standalone
    environment:
      - elo_rating=-1
      - game_timer_ms=150000
      - first_move_w=e2e4
      - hub_host=selenium-chess
      - hub_port=4444
    networks:
      - chess-bot
